### PR TITLE
ENH: add AT1K4-SOLID

### PR DESCRIPTION
**Pull request by klauer**
A few things:
* This will not build as-is: 10 states is beyond what `lcls-twincat-motion`supports at the moment.
* Only the "out" position has been defined for each (settings are from https://github.com/pcdshub/lcls-plc-sxr-satt#local-testing); beam-based measurements are required to determine the remainder.
* I added a couple function blocks here. I understand that these likely belong in the CC lib. I'm hoping we can try it out first here before rolling out and generalizing in the library.
* The most confusing part is the following, which I've attempted to add as comments in every spot I could:

```
    AT1K4 axes were mistakenly wired opposite to other solid attenuators.
    The intended convention is:
        MMS:01 should be the most upstream blade,
        MMS:04 should be the most downstream blade.

    The fix applied here is to reverse the pytmc pragmas:
        NC axis 2 is linked to M2, but is the most downstream axis MMS:04.
        NC axis 5 is linked to M5, but is the most upstream axis MMS:01.

    fbStage1 through fbStage4 correspond to axes 1 through 4 in the traveler.
    To keep the correct convention in EPICS, these are *reversed* here.
        fbStage1 (MMS:04)
        fbStage2 (MMS:03)
        fbStage3 (MMS:02)
        fbStage4 (MMS:01)
```

Rewiring the attenuator was deemed out of the question, so it appears this may be the best option. An alternative could have been renaming the rail elements and relinking - but somehow this _feels_ maybe a bit less error prone (and I spent way more time than I'd like to admit getting confused with the numbering already..)

Opinions are welcome, of course.

### CODE REVIEW

**Comment by klauer** [comment]
Lots of distractions today, sorry for the late PR.

Date-wise, it looks like next week is likely: "Fritz: If the vacuum scan looks good on Monday then it will be installed during the PAMM days. Hopefully the vacuum work will be completed on the first day."

**Comment by klauer** [comment]
Couple more notes:
* This **is not** on the list for this week's PAMM
* Style checks are failing for unrelated files - can handle this in a separate PR if desirable

**Comment by ZLLentz** [comment]
Is AT1K4 before or after the TMO FEE stoppers (ST1K4, ST2K4, and ST3K4)?

If after, this is the correct PLC

If before, this should actually be part of lcls-plc-kfe-motion since we moved all the IO to resolve an MPS issue

**Comment by klauer** [comment]
Before, according to:

image

For future reference and so that I can document it, is there somewhere I could have independently found this information? The placeholder in `lcls-plc-tmo-motion` this led to this project has ended up wasting a considerable amount of time.

**Comment by ZLLentz** [comment]
No, I suspect this is not documented well at all. There was a hint in the code but that's not good enough.
https://github.com/pcdshub/lcls-plc-tmo-motion/blob/37243646ce6e4d7fcf5f2c820f870fc8ff7e3a79/plc-tmo-motion/tmo_motion/GVLs/Main.TcGVL#L14

I'm sorry if this wasted a bunch of your time- I should have figured out how to remove the IO branch that is deactivated.

**Pull request closed without merging**
