### PR TITLE
changing at2k4 to pa1k4-pf

### PR DESCRIPTION
**Pull request by tongju12**
## Change device at2k4 to pa1k4-pf 

change all at2k4 related parts to pa1k4-pf
## Motivation and Context

Naming committee asks TMO to use pa1k4-pf instead of at2k4

## How Has This Been Tested?

Not yet. Because scientists do not want me to move, the hardware is not ready. 

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

### CODE REVIEW

**Comment by nrwslac** [comment]
Looks like simple name change. Does this build without errors? @tongju12. If so, could you update the how this was tested by including that.

**Comment by tongju12** [comment]
Nick, I log in with this build and can move any motors without issue. For P1K4-PF, I can move little bit but it is limited by PMPS setup. Currently, this motor hardware is not installed. So it is ok to let it go. I will come back to recheck this motor after hardware is installed.

**Comment by nrwslac** [comment]
I think in this case where the hardware names have changed it would be best to do a full activation to ensure that all the names and links restore correctly.

**Comment by tongju12** [comment]
I did Nick. I already activate configuration, log in and test a little bit already. Otherwise, it will not work.

**Pull request merged**
