### PR TITLE
ENH: enable temperature ffos, update temp sensor link names

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Apply the updates from https://github.com/pcdshub/lcls-twincat-common-components/releases/tag/v3.5.0, which enables fast faults on the common component temperature sensors.

This was manually duplicated on the ATMs which have special classes here.

For this PLC, the following devices are affected:
- IM2K4
- IM3K4
- IM4K4
- IM5K4
- IM6K4
- PF1K4
- PF2K4
- TM1K4
- TM2K4
- SP1K4 ATT

The expected behavior is that each target's temperature threshold from the PMPS database will be loaded and applied. That is: when the target is above a certain temperature, we will have a fast fault.

Fast faults are expected to clear themselves automatically if the device is removed, otherwise if the device is left in and cools down, the fast fault will need to be cleared using the PMPS UI.

## Motivation and Context

- We want to avoid melting TMO components with the higher power beam, so we shut the beam off if a temperature threshold is eclipsed.
- Related to https://jira.slac.stanford.edu/browse/ECS-4472

## How Has This Been Tested?

- Need to test with Tong today
- May or may not need to increase the number of FFO PVs

## Where Has This Been Documented?

Only here

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive comments
- [ ] ~Test suite passes locally~
- [x] Libraries are set to fixed versions and not ``Always Newest``
- [x] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

### CODE REVIEW

**Comment by ZLLentz** [comment]
I'm testing this with @tongju12 today before merging.
If it goes well, I'll propose doing similar patches to the kfe (@joshc-slac ) and rix (@jyotiphy ) common component motion PLCs in the coming weeks.

**Comment by ZLLentz** [comment]
I'm investigating why the screens don't quite work any more for TM1K4 and TM2K4. It's possible there could be one more edit to this, it's also possible that the fix will be in pcdsdevices.

**Comment by ZLLentz** [comment]
It seems like I needed to check my copy/paste pragmas more closely, I know what sort of thing needs to be fixed now. It's IOC-side only so I'm going to make the change, build, and rebuild the IOC but I'm not going to reactivate config.

**Comment by ZLLentz** [comment]
The missing PVs UI problem has been resolved now.

**Comment by ZLLentz** [comment]
Hi @tongju12 , should we merge this? Would you like a review from @ghalym or @NSLentz before we merge?

**Comment by tongju12** [comment]
Zach, if you think we do not need Maggie to check this, we should merge.
Thanks,
Tong

**Review by tongju12 — APPROVED** [review]
Zach and I test together and everything from PMPS function are all done.

**Pull request merged**
